config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'home#index'

  resources :restaurants do
    resources :dishes do
      get 'search', on: :collection
      post 'change_status', on: :member
      resources :features, only: [:new, :create]
      resources :menus, only: [:new, :create]

      resources :portions, controller: 'portions', type: 'Dish'
    end

    resources :drinks do
      get 'search', on: :collection
      post 'change_status', on: :member
      resources :features, only: [:new, :create]
      resources :menus, only: [:new, :create]
      resources :portions, controller: 'portions', type: 'Drink'
    end

    resources :operating_hours
    resources :employees, only: [:new, :index, :create]
    resources :features
    resources :menus
    resources :orders
  end

  namespace :api do
    namespace :v1 do
        get 'restaurants/:restaurant_alphanumeric_code/orders/:order_alphanumeric_code', to: 'orders#show', as: 'show'
        patch 'restaurants/:restaurant_alphanumeric_code/orders/:order_alphanumeric_code', to: 'orders#update', as: 'update'
        get 'restaurants/:restaurant_alphanumeric_code/orders/', to: 'orders#index', as: 'index'
    end
  end
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :restaurant
  has_one_attached :image
  has_many :portions, as: :portionable, dependent: :destroy

  has_many :item_features, as: :featurable
  has_many :features, through: :item_features

  has_many :menu_items, as: :menu_itemable
  has_many :menus, through: :menu_items

  validates :name, :description, :restaurant_id, presence: true
  
  enum status: { active: 1, inactive: 0 }
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :redirect_unless_restaurant
  before_action :set_restaurant
  before_action :authenticate_user!
  before_action :user_have_permition
  before_action :user_is_owner

  def index
    @features = @restaurant.features
    @drinks = @restaurant.drinks
    if params[:feature_ids] 
      @drinks = @drinks.joins(:features).where(features: { id: params[:feature_ids] }).distinct
    end
  end

  def show
    if params[:feature_ids].present?
      @drink = @restaurant.drinks.includes(:features).where(features: { id: params[:feature_ids] }).distinct
    else
      @drink = @restaurant.drinks.find(params[:id])
      @portions = @drink.portions
    end
  end

  def edit
    @features = @restaurant.features
    @drink = @restaurant.drinks.find(params[:id])
  end

  def new
    @drink = @restaurant.drinks.build
  end

  def update
    @drink = @restaurant.drinks.find(params[:id])
    if @drink.update(drink_params)
      if params[:feature_ids] 
        params[:feature_ids].each do |feature_id|
          feature = Feature.find(feature_id)
          ItemFeature.create!(feature: feature, featurable: @drink)
        end
      end
      redirect_to restaurant_drinks_path(current_user.restaurant), notice: I18n.t('drinks.update_success')
    else
      flash.now[:notice] = I18n.t('drinks.update_fail')
      render 'edit', status: :unprocessable_entity
    end
  end

  def create
    @drink = @restaurant.drinks.build(drink_params)
    if @drink.save
      redirect_to restaurant_drink_path(@restaurant, @drink), notice: I18n.t('drinks.create_success')
    else
      flash.now[ :alert ] = I18n.t('drinks.create_fail')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @drink = @restaurant.drinks.find(params[:id])
    @drink.destroy
    redirect_to restaurant_drinks_path(@restaurant), notice: I18n.t('drinks.destroy_success')
  end

  def search
    @find = params["query"]
    @drinks = @restaurant.drinks.where("name LIKE ? OR description LIKE ?", "%#{@find}%", "%#{@find}%").all
    @features = ItemFeature.where(featurable_type: "Drink")
    if params[:feature_ids] 
      @drinks = @drinks.joins(:features).where(features: { id: params[:feature_ids] }).distinct
    end
  end

  def change_status
    @drink = @restaurant.drinks.find(params[:id])
    if @drink.active? 
      @drink.inactive!
    else 
      @drink.active!
    end
    redirect_to restaurant_drink_path(@restaurant, @drink)
  end

  private

  def user_is_owner
    if current_user.employee?
      redirect_to root_path, alert: I18n.t('drinks.no_permition')
    end
  end

  def user_have_permition
    if @restaurant.id != current_user.restaurant_id
      redirect_to root_path, alert: I18n.t('drinks.no_permition')
    end
  end
  
  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def redirect_unless_restaurant
    if current_user.restaurant_id.nil?
      flash.now[:notice] = I18n.t('drinks.no_permition')
      redirect_to new_restaurant_path
    end
  end

  def drink_params
    params.require(:drink).permit(:name, :description, :alcohol, :image)
  end
end

app/views/drinks/edit.html.erb
<div class="container mt-5">
  <h1><%= I18n.t('drinks.add_info') %>:</h1>

  <% if @drink.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @drink.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: [current_user.restaurant, @drink], local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "form-label" %>
      <%= f.text_field :description, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :alcohol, class: "form-label" %>
      <%= f.check_box :alcohol, class: "form-check-input" %>
    </div>

    <div class="form-group">
      <%= f.label Drink.human_attribute_name(:image), class: "form-label" %>
      <% if @drink.image.attached? %>
        <div class="image-preview">
          <%= image_tag @drink.image, size: "100x100", alt: @drink.name %>
        </div>
        <%= f.file_field :image, class: "form-control" %>
      <% else %>
        <p><%= I18n.t('.no_img') %></p>
      <% end %>
    </div>

    <% if @drink.features.any? %>
      <h5><%= I18n.t('.contains') %>:</h5>
      <ul>
        <% @drink.features.each do |drink_feature| %>
          <li><%= drink_feature.name %></li>
        <% end %>
      </ul>
    <% end %>

    <p><%= I18n.t('.add_feature') %>:</p>
    <div class="form-group">
      <% @features.each do |feature| %>
        <div class="form-check">
          <%= check_box_tag "feature_ids[]", feature.id, params[:feature_ids]&.include?(feature.id.to_s), class: "form-check-input" %>
          <%= label_tag "feature_ids_#{feature.id}", feature.name, class: "form-check-label" %>
        </div>
      <% end %>
    </div>

    <%= f.submit I18n.t('drinks.save_drink'), class: "btn btn-primary" %>
  <% end %>

  <%= button_to I18n.t('drinks.del_drink'), restaurant_drink_path(current_user.restaurant, @drink), method: :delete, class: "btn btn-danger mt-3", data: { confirm: I18n.t('drinks.confirm_delete') } %>
</div>

app/views/drinks/index.html.erb
<div class="container mt-5">
  <h1><%= I18n.t('drinks.drink_list') %></h1>
  
  <p><%= link_to I18n.t('drinks.new_drink'), new_restaurant_drink_path, class: "btn btn-primary mb-3" %></p>

  <%= form_with(url: restaurant_drinks_path(@restaurant), method: :get, local: true, class: "mb-3") do %>
    <h3><%= I18n.t('drinks.filter_by_features') %>:</h3>
    
    <% @features.each do |feature| %>
      <div class="form-check">
        <%= check_box_tag "feature_ids[]", feature.id, params[:feature_ids]&.include?(feature.id.to_s), class: "form-check-input" %>
        <%= label_tag "feature_ids_#{feature.id}", feature.name, class: "form-check-label" %>
      </div>
    <% end %>
    
    <%= submit_tag I18n.t('.filter'), class: "btn btn-secondary mt-3" %>
  <% end %>

  <p><%= link_to I18n.t('drinks.feature_list'), restaurant_features_path, class: "btn btn-link" %></p>

  <% if @drinks.present? %> 
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= I18n.t('.picture') %></th>
          <th><%= Drink.human_attribute_name(:name) %></th>
          <th><%= Drink.human_attribute_name(:description) %></th>
          <th><%= I18n.t('drinks.have_alcohol') %></th>
          <th><%= I18n.t('.contains') %></th>
          <th><%= Drink.human_attribute_name(:status) %></th>
          <th><%= I18n.t('.action') %></th>
        </tr>
      </thead>
      <tbody>
        <% @drinks.each do |d| %>
          <tr>
            <td>
              <% if d.image.attached? %>
                <%= image_tag d.image, size: "100x100", alt: d.name, class: "img-fluid" %>
              <% else %>
                <p><%= I18n.t('.no_img') %></p>
              <% end %>
            </td>
            <td><%= d.name %></td>
            <td><%= d.description %></td>
            <td><%= d.alcohol ? "Sim" : "Não" %></td>
            <td>
              <% d.features.each do |drink_feature| %>
                <span class="badge badge-info" style="color: black;"><%= drink_feature.name %></span>
              <% end %>
            </td>
            <td><%= I18n.translate(d.status) %></td>
            <td>
              <%= link_to "#{I18n.t('.details')} #{d.name}", restaurant_drink_path(current_user.restaurant, d), class: "btn btn-info btn-sm" %> |
              <%= link_to "#{I18n.t('.edit')} #{d.name}", edit_restaurant_drink_path(current_user.restaurant, d), class: "btn btn-warning btn-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p><%= I18n.t('drinks.no_drinks') %></p>
  <% end %>
</div>

app/views/drinks/new.html.erb
<h1><%= I18n.t('drinks.add_info') %>:</h1>

<% if @drink.errors.any? %>
  <ul>
    <% @drink.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: [current_user.restaurant, @drink]) do |f| %>
  <dl class="row">
    <dt class="col-sm-2"><%= f.label :name %></dt>
    <dd class="col-sm-10"><%= f.text_field :name, class: "form-control" %></dd>

    <dt class="col-sm-2"><%= f.label :description %></dt>
    <dd class="col-sm-10"><%= f.text_field :description, class: "form-control" %></dd>

    <dt class="col-sm-2"><%= f.label :alcohol %></dt>
    <dd class="col-sm-10"><%= f.check_box :alcohol %></dd>

    <dt class="col-sm-2"><%= f.label :image %></dt>
    <dd class="col-sm-10">
      <%= f.file_field :image, class: "form-control" %>
      <% if @drink.image.attached? %>
        <p><%= image_tag @drink.image, size: "100x100", alt: @drink.name %></p>
      <% else %>
        <p><%= I18n.t('.no_img') %></p>
      <% end %>
    </dd>
  </dl>

  <%= f.submit I18n.t('drinks.save_drink'), class: "btn btn-primary" %>
<% end %>

app/views/drinks/search.html.erb
<h1><%= I18n.t('drinks.drinks_found') %>: <%= @find %></h1>

<p><%= link_to I18n.t('drinks.new_drink'), new_restaurant_drink_path, class: 'btn btn-primary' %></p>

<%= form_with(url: restaurant_drinks_path(@restaurant), method: :get, local: true) do %>
  <h3><%= I18n.t('drinks.filter_by_features') %>:</h3>
  
  <% @features.each do |feature| %>
    <div class="form-check">
      <%= check_box_tag "feature_ids[]", feature.feature.id, params[:feature_ids]&.include?(feature.feature.id.to_s), class: 'form-check-input' %>
      <%= label_tag "feature_ids_#{feature.feature.id}", feature.feature.name, class: 'form-check-label' %>
    </div>
  <% end %>

  <%= submit_tag I18n.t('.filter'), class: 'btn btn-secondary' %>
<% end %>

<% if @drinks.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= I18n.t('.picture') %></th>
        <th><%= Drink.human_attribute_name(:name) %></th>
        <th><%= Drink.human_attribute_name(:description) %></th>
        <th><%= I18n.t('.contains') %></th>
        <th><%= I18n.t('drinks.have_alcohol') %></th>
        <th><%= Drink.human_attribute_name(:status) %></th>
        <th><%= I18n.t('.action') %></th>
      </tr>
    </thead>
    <tbody>
      <% @drinks.each do |drink| %>
        <tr>
          <td>
            <% if drink.image.attached? %>
              <%= image_tag drink.image, size: "100x100", alt: drink.name %>
            <% else %>
              <p><%= I18n.t('.no_img') %></p>
            <% end %>
          </td>
          <td><%= drink.name %></td>
          <td><%= drink.description %></td>
          <td>
            <% drink.features.each do |drink_feature| %>
              <%= drink_feature.name %><br>
            <% end %>
          </td>
          <td><%= drink.alcohol ? I18n.t('.yes') : I18n.t('.no') %></td>
          <td><%= I18n.t(drink.status) %></td>
          <td>
            <%= link_to "#{I18n.t('.details')} #{drink.name}", restaurant_drink_path(current_user.restaurant, drink), class: 'btn btn-info btn-sm' %> |
            <%= link_to "#{I18n.t('.edit')} #{drink.name}", edit_restaurant_drink_path(current_user.restaurant, drink), class: 'btn btn-warning btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1><%= I18n.t('drinks.drinks_not_found') %></h1>
<% end %>

app/views/drinks/show.html.erb
<h1><%= @drink.name %> - <%= I18n.t('drinks.details') %></h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= I18n.t('.picture') %></th>
      <th><%= Drink.human_attribute_name(:name) %></th>
      <th><%= Drink.human_attribute_name(:description) %></th>
      <th><%= I18n.t('drinks.have_alcohol') %></th>
      <th><%= I18n.t('.contains') %></th>
      <th><%= Drink.human_attribute_name(:status) %></th>
      <th><%= I18n.t('.action') %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <% if @drink.image.attached? %>
          <%= image_tag @drink.image, size: "100x100", alt: @drink.name, class: 'img-thumbnail' %>
        <% else %>
          <p><%= I18n.t('.no_img') %></p>
        <% end %>
      </td>
      <td><%= @drink.name %></td>
      <td><%= @drink.description %></td>
      <td><%= @drink.alcohol ? I18n.t('.yes') : I18n.t('.no') %></td>
      <td>
        <% @drink.features.each do |drink_feature| %>
          <%= drink_feature.name %><br>
        <% end %>
      </td>
      <td><%= I18n.t(@drink.status) %></td>
      <td>
        <%= button_to I18n.t('drinks.change_status'), change_status_restaurant_drink_path(@restaurant, @drink), class: 'btn btn-warning btn-sm' %>
        <%= link_to I18n.t('.edit'), edit_restaurant_drink_path(current_user.restaurant, @drink), class: 'btn btn-primary btn-sm' %>
      </td>
    </tr>
  </tbody>
</table>

<% if @drink.portions.present? %>
  <h2><%= I18n.t('drinks.portions_list') %>:</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= I18n.t('portions.description_of') %></th>
        <th><%= I18n.t('.price') %></th>
      </tr>
    </thead>
    <tbody>
      <% @drink.portions.each do |portion| %>
        <tr>
          <td><%= portion.description %></td>
          <td><%= number_to_currency(portion.price_whole + portion.price_cents / 100.0, unit: I18n.t('.number.currency.format.unit')) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p><%= I18n.t('drinks.no_portion') %>.</p>
<% end %>

<p><%= link_to I18n.t('.portions.add_portion'), new_restaurant_drink_portion_path(@restaurant, @drink), class: 'btn btn-success' %></p>
<%= link_to I18n.t('.go_back'), restaurant_drinks_path(@drink.restaurant), class: 'btn btn-secondary' %>