config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'home#index'

  resources :restaurants do
    resources :dishes do
      get 'search', on: :collection
      post 'change_status', on: :member
      resources :features, only: [:new, :create]
      resources :menus, only: [:new, :create]

      resources :portions, controller: 'portions', type: 'Dish'
    end

    resources :drinks do
      get 'search', on: :collection
      post 'change_status', on: :member
      resources :features, only: [:new, :create]
      resources :menus, only: [:new, :create]
      resources :portions, controller: 'portions', type: 'Drink'
    end

    resources :operating_hours
    resources :employees, only: [:new, :index, :create]
    resources :features
    resources :menus
    resources :orders
  end

  namespace :api do
    namespace :v1 do
        get 'restaurants/:restaurant_alphanumeric_code/orders/:order_alphanumeric_code', to: 'orders#show', as: 'show'
        patch 'restaurants/:restaurant_alphanumeric_code/orders/:order_alphanumeric_code', to: 'orders#update', as: 'update'
        get 'restaurants/:restaurant_alphanumeric_code/orders/', to: 'orders#index', as: 'index'
    end
  end
end

app/models/portion.rb
class Portion < ApplicationRecord
  belongs_to :portionable, polymorphic: true

  has_many :order_items
  has_many :orders, through: :order_items
end

app/controllers/portions_controller.rb
class PortionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_dish_or_drink
  before_action :redirect_unless_restaurant
  before_action :user_have_permition
  before_action :user_is_owner
  

  def index
    authorize_access
    @portions = @portionable.portions
  end

  def show
    authorize_access
    @portion = @portionable.portions.find(params[:id])
  end

  def new
    @portion = @portionable.portions.build
  end

  def create
    @portion = @portionable.portions.build(portion_params)
    if @portion.save
      if (params[:dish_id])
        redirect_to restaurant_dish_path(@restaurant, @portionable), notice: 'Porção cadastrada com sucesso'
      else
        redirect_to restaurant_drink_path(@restaurant, @portionable), notice: 'Porção cadastrada com sucesso'
      end
    else
      flash.now[:alert] = 'Não foi possível cadastrar a porção'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize_access
    @portion = Portion.find params[:id]
  end

  def update
    @portion = @restaurant.portions.find(params[:id])
    if @portion.update(portion_params)
      redirect_to restaurant_portions_path(@restaurant), notice: 'Porção atualizada com sucesso'
    else
      flash.now[:alert] = "Não foi possível atualizar a porção"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize_access
    @portion = @restaurant.portions.find(params[:id])
    if @portion.destroy
      redirect_to restaurant_portions_path(@restaurant), notice: 'Porção deletada com sucesso'
    else
      redirect_to restaurant_portions_path(@restaurant), alert: 'Erro ao deletar a porção'
    end
  end

  private

  def user_is_owner
    if current_user.employee?
      redirect_to root_path, alert: 'Você não possui acesso a esta lista'
    end
  end

  def user_is_owner
    if current_user.employee?
      redirect_to root_path, alert: 'Você não possui acesso a esta lista'
    end
  end

  def user_have_permition
    if @restaurant.id != current_user.restaurant_id
      redirect_to root_path, alert: 'Você não possui acesso a esta lista'
    end
  end

  def set_dish_or_drink
    if (params[:dish_id])
      @portionable = @restaurant.dishes.find(params[:dish_id])
    else
      @portionable = @restaurant.drinks.find(params[:drink_id])     
    end
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def redirect_unless_restaurant
    if current_user.restaurant_id.nil?
      flash.now[:notice] = 'Você não tem permissão para acessar esse restaurante.'
      redirect_to new_restaurant_path
    end
  end


  def portion_params
    params.require(:portion).permit(:description, :price_whole, :price_cents, :portionable_type, :portionable_id)
  end
end

app/views/portions/index.html.erb
<div class="container mt-5">
  <h1><%= I18n.t('portions.list_portoin_to') %> <%= @dish.name %></h1>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th><%= Portion.human_attribute_name(:description) %></th>
        <th><%= I18n.t('.price') %></th>
        <th><%= I18n.t('.action') %></th>
      </tr>
    </thead>
    <tbody>
      <% @portions.each do |portion| %>
        <tr>
          <td><%= portion.description %></td>
          <td><%= I18n.t('.number.currency.format.unit') %> <%= portion.price_whole %>,<%= portion.price_cents %></td>
          <td>
            <%= link_to I18n.t('.show'), restaurant_dish_portion_path(@restaurant, @dish, portion), class: "btn btn-info btn-sm" %>
            <%= link_to I18n.t('.edit'), edit_restaurant_dish_portion_path(@restaurant, @dish, portion), class: "btn btn-warning btn-sm" %>
            <%= link_to I18n.t('.exclude'), restaurant_dish_portion_path(@restaurant, @dish, portion), method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <p>
    <%= link_to I18n.t('portions.new_portion'), new_restaurant_dish_portion_path(@restaurant, @dish), class: "btn btn-primary" %>
  </p>
</div>

app/views/portions/new.html.erb
<div class="container mt-5">
  <h1><%= I18n.t('portions.add_info') %>:</h1>

  <% if @portion.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @portion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: [@restaurant, @portionable, @portion], local: true) do |f| %>
    <div class="mb-3">
      <%= f.label :description, I18n.t('portions.description_of'), class: 'form-label' %>
      <%= f.text_field :description, required: true, class: 'form-control', placeholder: I18n.t('portions.exemple_description') %>
    </div>

    <div class="mb-3">
      <%= f.label :price_whole, "#{I18n.t('.price')} (#{I18n.t('portions.price_whole')} - #{I18n.t('.number.currency.format.unit')})", class: 'form-label' %>
      <%= f.number_field :price_whole, required: true, class: 'form-control', placeholder: "Ex.: 45" %>
    </div>

    <div class="mb-3">
      <%= f.label :price_cents, "#{I18n.t('.price')} (#{I18n.t('portions.price_cents')})", class: 'form-label' %>
      <%= f.number_field :price_cents, required: true, class: 'form-control', placeholder: I18n.t('portions.exemple_price') %>
    </div>

    <div>
      <%= f.submit I18n.t('portions.save_portion'), class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/portions/show.html.erb
<div class="container mt-5">
  <h1><%= I18n.t('portions.details') %></h1>

  <div class="mb-3">
    <p><strong><%= Portion.human_attribute_name(:description) %>:</strong> <%= @portion.description %></p>
  </div>

  <div class="mb-3">
    <p><strong><%= I18n.t('.price') %>:</strong> <%= I18n.t('.number.currency.format.unit') %> <%= @portion.price_whole %>,<%= @portion.price_cents %></p>
  </div>

  <div>
    <%= link_to I18n.t('.edit'), edit_restaurant_dish_portion_path(@restaurant, @dish, @portion), class: 'btn btn-warning btn-sm' %>
    <%= link_to I18n.t('portions.back_to_portions'), restaurant_dish_portions_path(@restaurant, @dish), class: 'btn btn-secondary btn-sm' %>
  </div>
</div>