config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'home#index'

  resources :restaurants do
    resources :dishes do
      get 'search', on: :collection
      post 'change_status', on: :member
      resources :features, only: [:new, :create]
      resources :menus, only: [:new, :create]

      resources :portions, controller: 'portions', type: 'Dish'
    end

    resources :drinks do
      get 'search', on: :collection
      post 'change_status', on: :member
      resources :features, only: [:new, :create]
      resources :menus, only: [:new, :create]
      resources :portions, controller: 'portions', type: 'Drink'
    end

    resources :operating_hours
    resources :employees, only: [:new, :index, :create]
    resources :features
    resources :menus
    resources :orders
  end

  namespace :api do
    namespace :v1 do
        get 'restaurants/:restaurant_alphanumeric_code/orders/:order_alphanumeric_code', to: 'orders#show', as: 'show'
        patch 'restaurants/:restaurant_alphanumeric_code/orders/:order_alphanumeric_code', to: 'orders#update', as: 'update'
        get 'restaurants/:restaurant_alphanumeric_code/orders/', to: 'orders#index', as: 'index'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Paleva" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">      
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" 
              data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" 
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
            
      <div class="navbar-collapse collapse" id="navbarsExampleDefault">
        <% if user_signed_in? %>
          <ul class="navbar-nav mr-auto">
            <% if current_user.restaurant&.persisted? %>
              <%= link_to "#{current_user.restaurant.trade_name}", root_path, class: "navbar-brand" %>
              <li class="nav-item active">
                <%= link_to I18n.t('.restaurant'), restaurant_path(current_user.restaurant), class: "nav-link" %>
              </li>
              <% if current_user.owner? %>
                <li class="nav-item">
                  <%= link_to I18n.t('dishes.all_dish'), restaurant_dishes_path(current_user.restaurant), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to I18n.t('drinks.all_drink'), restaurant_drinks_path(current_user.restaurant), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to I18n.t('operating_hours.hours_list'), restaurant_operating_hours_path(current_user.restaurant), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= form_with(url: search_restaurant_dishes_path(current_user.restaurant), method: :get, class: "form-inline d-flex") do |f| %>
                    <%= f.text_field :query, id: 'search_dish', class: "form-control mr-sm-2" %>
                    <%= f.submit I18n.t('dishes.search_dishes'), class: "btn btn-outline-success my-2 my-sm-0" %>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= form_with(url: search_restaurant_drinks_path(current_user.restaurant), method: :get, class: "form-inline d-flex") do |f| %>
                    <%= f.text_field :query, id: 'search_drink', class: "form-control mr-sm-2" %>
                    <%= f.submit I18n.t('drinks.search_drinks'), class: "btn btn-outline-success my-2 my-sm-0" %>
                  <% end %>
                </li>
              <% end %>
            <% else %>
              <li class="nav-item active">
                <%= link_to I18n.t('restaurants.new_restaurant'), new_restaurant_path, class: "nav-link" %>
              </li>
            <% end %>
            <li class="nav-item">
              <p style="color: #fff; margin: 0; padding: 10px;">
                <%= "#{I18n.t('.hello')}, #{current_user.first_name}" %>
              </p>
            </li>
            <li class="nav-item">
              <%= button_to I18n.t('.exit'), destroy_user_session_path, method: :delete, class: "btn btn-outline-success my-2 my-sm-0" %>
            </li>
          </ul>
        <% else %>
        <%= link_to 'PaLevá', root_path, class: "navbar-brand" %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to I18n.t('.join'), new_user_session_path, class: "nav-link" %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
  </header>

  <main role="main">
    <div class="jumbotron">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </main>
</body>
</html>